"""Add image_compress field for task

Revision ID: 117c1978d
Revises: 3930aac13b84
Create Date: 2014-10-30 16:11:50.479239

"""

# revision identifiers, used by Alembic.
revision = '117c1978d'
down_revision = '3930aac13b84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_compress', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'image_compress')
    ### end Alembic commands ###
