"""Add vendor table.

Revision ID: 3b216bebddbb
Revises: 50b790a6eef8
Create Date: 2014-10-29 02:57:52.259739

"""

# revision identifiers, used by Alembic.
revision = '3b216bebddbb'
down_revision = '50b790a6eef8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('price_range', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_vendors',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='cascade')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_vendors')
    op.drop_table('vendors')
    ### end Alembic commands ###
