"""Tasks: Add workload and required field.

Revision ID: 50b790a6eef8
Revises: 316cb332029a
Create Date: 2014-10-21 15:08:21.064818

"""

# revision identifiers, used by Alembic.
revision = '50b790a6eef8'
down_revision = '316cb332029a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('required', sa.Boolean(),
                                     server_default='1'))
    op.add_column('tasks', sa.Column('workload', sa.Integer(),
                                     server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'workload')
    op.drop_column('tasks', 'required')
    ### end Alembic commands ###
