"""Init db.

Revision ID: d75d5f90d3
Revises: None
Create Date: 2014-10-05 22:11:44.386767

"""

# revision identifiers, used by Alembic.
revision = 'd75d5f90d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('when', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('wedding_date', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('task_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tutorial', sa.Text(), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_tasks',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('series_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_task_id'], ['tasks.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='cascade')
    )
    op.create_table('tasks_scenarios',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='cascade')
    )
    op.create_table('related_tasks',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('related_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='cascade')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_tasks')
    op.drop_table('tasks_scenarios')
    op.drop_table('series_tasks')
    op.drop_table('tasks')
    op.drop_table('users')
    op.drop_table('scenarios')
    ### end Alembic commands ###
